version: 2
jobs:
  build:
    docker:
      - image: haessal/cmisc-builder:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: check compiler version
          command: gcc --version
      - run:
          name: build all
          command: make
