version: 2
jobs:
  build:
    docker:
      - image: haessal/cmisc-builder:latest
    working_directory: ~/cMisc
    steps:
      - checkout
      - run:
          name: check compiler version
          command: gcc --version
      - run:
          name: build all
          command: |
            make
            make clean
      - run:
          name: unit test and report coverage
          command: |
            make test
            rm gtest_*.gcda gtest_*.gcno
            bash <(curl -s https://codecov.io/bash)
            lcov -c -d . -o ./googletest.info
            genhtml -o ./coverage ./googletest.info
            make clean
      - store_artifacts:
          path: coverage
